# -*- coding: utf-8 -*-
"""sentiment_wrapper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLSMuxiPpv2vfQDm-AcIh-8SMGW5gJNw
"""



import joblib

class SentimentAnalyzer:
    def __init__(self, model_path, low=0.4, high=0.6):
        self.model = joblib.load(model_path)
        self.low = low
        self.high = high

    def predict(self, texto: str):
        proba = self.model.predict_proba([texto])[0]
        neg, pos = proba

        if self.low < pos < self.high:
            return {
                "sentimiento": "NEUTRO",
                "confianza": round(max(pos, neg), 4),
                "positivo": pos,
                "negativo": neg
            }

        return {
            "sentimiento": "POSITIVO" if pos >= self.high else "NEGATIVO",
            "confianza": round(max(pos, neg), 4),
            "positivo": pos,
            "negativo": neg
        }