# Configuración específica para Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.vgyqctkucenzhrjvowzr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
